# Generated by Django 3.0.2 on 2020-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_Id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('details', models.TextField()),
                ('developer', models.BooleanField(default=False)),
                ('business_dev', models.BooleanField(default=False)),
            ],
        ),
    ]
